Repository kpicaza/monorepo-test, pull requests merged in 2021-06, with the labels that each got.

#4 test automatic changelogs
  .github/workflows/generate_changelog.yaml
  packages/first-package/.github/workflows/generate_changelog.yaml
  packages/second-package/.github/workflows/generate_changelog.yaml
Labels: bug, enhancement

#7 [first-package] ueueueue
  .github/workflows/generate_changelog.yaml
Labels: enhancement

#8 [second-package] a ver si esta ya...
  .github/workflows/generate_changelog.yaml
Labels: bug

#12 [first-package] Comment generate_changelog_yaml
  .github/workflows/generate_changelog.yaml
Labels: bug

#14 [second-package] Add git status + working directory
  .github/workflows/generate_changelog.yaml
  .github/workflows/generate_split_changelog.yaml
Labels: bug

#16 [first-package] Fix working-directory
  .github/workflows/generate_split_changelog.yaml
Labels: bug

#17 [first-package] Fix working-directory
  .github/workflows/generate_split_changelog.yaml
Labels: bug

#18 [first-package] Remove wrong step
  .github/workflows/generate_split_changelog.yaml
Labels: bug
